import { definePreset } from '@primeng/themes';
import Aura from '@primeng/themes/aura';

export const PrimeCustomPreset = definePreset(Aura, {
  semantic: {
    primary: {
      50: '#fdc570',
      100: '#fdc570',
      200: '#fdc570',
      300: '#f87b07',
      400: '#f87b07',
      500: '#f87b07',
      600: '#f87b07',
      700: '#f87b07',
      800: '#fdc570',
      900: '#fdc570',
      950: '#fdc570',
    },
    secondary: {
      50: '#212522',
      100: '#212522',
      200: '#212522',
      300: '#212522',
      400: '#212522',
      500: '#212522',
      600: '#212522',
      700: '#212522',
      800: '#212522',
      900: '#212522',
      950: '#212522',
    },
    colorScheme: {
      light: {
        primary: {
          color: '#f87b07',
          contrastColor: '#ffffff',
          hoverColor: '#fdc570',
          activeColor: 'rgb(46, 38, 26)',
        },
        highlight: {
          background: '#f87b07',
          focusBackground: '#fdc570',
          color: '#ffffff',
          focusColor: '#f8f9fa',
        },
        surface: {
          0: '#ffffff',
          50: '#f8f9fa',
          100: '#f1f3f4',
          200: '#e8eaed',
          300: '#dadce0',
          400: '#bdc1c6',
          500: '#9aa0a6',
          600: '#80868b',
          700: '#5f6368',
          800: '#3c4043',
          900: '#202124',
          950: '#171717',
        },
        content: {
          color: '#212529',
          hoverColor: '#f87b07',
          activeColor: 'rgb(46, 38, 26)',
        },
      },
      dark: {
        primary: {
          color: '#fdc570',
          contrastColor: '#000000',
          hoverColor: '#f87b07',
          activeColor: 'rgb(46, 38, 26)',
        },
        highlight: {
          background: '#fdc570',
          focusBackground: '#f87b07',
          color: '#000000',
          focusColor: '#1a1d23',
        },
        surface: {
          0: '#1a1a1a',
          50: '#1e1e1e',
          100: '#222222',
          200: '#262626',
          300: '#2a2a2a',
          400: '#404040',
          500: '#4f4f4f',
          600: '#5e5e5e',
          700: '#6d6d6d',
          800: '#7c7c7c',
          900: '#8b8b8b',
          950: '#9a9a9a',
        },
        content: {
          color: '#f8f9fa',
          hoverColor: '#fdc570',
          activeColor: '#f87b07',
        },
      },
    },
  },
  components: {
    toolbar: {
      colorScheme: {
        light: {
          root: {
            background: '#e8eaed',
            borderColor: '#dadce0',
            color: '#212529',
            borderRadius: '0',
            padding: '0.05rem 0.8rem 0.05rem 0.05rem',
          },
        },
        dark: {
          root: {
            background: '#1c232c',
            borderColor: '#2a2a2a',
            color: '#e9ecef',
            borderRadius: '0',
            padding: '0.05rem 0.8rem 0.05rem 0.05rem',
          },
        },
      },
    },
    button: {
      colorScheme: {
        light: {
          root: {
            primary: {
              background: '#f87b07',
              hoverBackground: '#fdc570',
              activeBackground: 'rgb(46, 38, 26)',
              borderColor: '#f87b07',
              hoverBorderColor: '#fdc570',
              activeBorderColor: 'rgb(46, 38, 26)',
              color: '#ffffff',
              hoverColor: '#ffffff',
              activeColor: '#ffffff',
            },
            secondary: {
              background: 'rgb(46, 38, 26)',
              hoverBackground: '#6c757d',
              activeBackground: '#adb5bd',
              borderColor: 'rgb(46, 38, 26)',
              hoverBorderColor: '#6c757d',
              activeBorderColor: '#adb5bd',
              color: '#ffffff',
              hoverColor: '#ffffff',
              activeColor: '#ffffff',
            },
            success: {
              background: 'rgb(46, 38, 26)',
              hoverBackground: '#fdc570',
              activeBackground: '#f87b07',
              borderColor: 'rgb(46, 38, 26)',
              hoverBorderColor: '#fdc570',
              activeBorderColor: '#f87b07',
              color: '#ffffff',
              hoverColor: '#ffffff',
              activeColor: '#ffffff',
            },
            warn: {
              background: '#ff9914',
              hoverBackground: '#ff9914',
              activeBackground: '#ff9914',
              borderColor: '#ff9914',
              hoverBorderColor: '#ff9914',
              activeBorderColor: '#ff9914',
              color: '#000000',
              hoverColor: '#000000',
              activeColor: '#ffffff',
            },
            danger: {
              background: '#f21b3f',
              hoverBackground: '#f21b3f',
              activeBackground: '#f21b3f',
              borderColor: '#f21b3f',
              hoverBorderColor: '#f21b3f',
              activeBorderColor: '#f21b3f',
              color: '#ffffff',
              hoverColor: '#ffffff',
              activeColor: '#ffffff',
            },
          },
        },
        dark: {
          root: {
            primary: {
              background: '#fdc570',
              hoverBackground: '#f87b07',
              activeBackground: 'rgb(46, 38, 26)',
              borderColor: '#fdc570',
              hoverBorderColor: '#f87b07',
              activeBorderColor: 'rgb(46, 38, 26)',
              color: '#000000',
              hoverColor: '#000000',
              activeColor: '#000000',
            },
            secondary: {
              background: '#adb5bd',
              hoverBackground: '#6c757d',
              activeBackground: '#212529',
              borderColor: '#adb5bd',
              hoverBorderColor: '#6c757d',
              activeBorderColor: '#212529',
              color: '#000000',
              hoverColor: '#000000',
              activeColor: '#000000',
            },
            success: {
              background: 'rgb(46, 38, 26)',
              hoverBackground: '#fdc570',
              activeBackground: '#f87b07',
              borderColor: 'rgb(46, 38, 26)',
              hoverBorderColor: '#fdc570',
              activeBorderColor: '#f87b07',
              color: '#ffffff',
              hoverColor: '#ffffff',
              activeColor: '#ffffff',
            },
            warn: {
              background: '#ff9914',
              hoverBackground: '#ff9914',
              activeBackground: '#ff9914',
              borderColor: '#ff9914',
              hoverBorderColor: '#ff9914',
              activeBorderColor: '#ff9914',
              color: '#000000',
              hoverColor: '#000000',
              activeColor: '#000000',
            },
            danger: {
              background: '#f21b3f',
              hoverBackground: '#f21b3f',
              activeBackground: '#f21b3f',
              borderColor: '#f21b3f',
              hoverBorderColor: '#f21b3f',
              activeBorderColor: '#f21b3f',
              color: '#ffffff',
              hoverColor: '#ffffff',
              activeColor: '#ffffff',
            },
          },
        },
      },
    },
    card: {
      colorScheme: {
        light: {
          root: {
            background: '#f8f9fa',
            color: '#212529',
          },
          subtitle: {
            color: '#6c757d',
          },
        },
        dark: {
          root: {
            background: '#1a1d23',
            color: '#e9ecef',
          },
          subtitle: {
            color: '#adb5bd',
          },
        },
      },
    },
    panel: {
      colorScheme: {
        light: {
          root: {
            background: '#f8f9fa',
            borderColor: '#adb5bd',
            color: '#212529',
          },
          header: {
            background: '#f8f9fa',
            borderColor: '#adb5bd',
            color: '#f87b07',
          },
        },
        dark: {
          root: {
            background: '#1a1d23',
            borderColor: '#212529',
            color: '#e9ecef',
          },
          header: {
            background: '#1a1d23',
            borderColor: '#212529',
            color: '#fdc570',
          },
        },
      },
    },
    tabs: {
      colorScheme: {
        light: {
          root: {
            transitionDuration: '0.2s',
          },
          tablist: {
            borderWidth: '0 0 2px 0',
            background: '#f8f9fa',
            borderColor: '#e9ecef',
          },
          tab: {
            background: 'transparent',
            hoverBackground: '#fdc570',
            activeBackground: '#f87b07',
            borderWidth: '0 0 2px 0',
            borderColor: 'transparent',
            hoverBorderColor: '#fdc570',
            activeBorderColor: '#f87b07',
            color: '#6c757d',
            hoverColor: '#212529',
            activeColor: '#ffffff',
            padding: '1rem 1.25rem',
            fontWeight: '600',
            margin: '0 0 -2px 0',
            gap: '0.5rem',
            focusRing: {
              width: '0',
              style: 'none',
              color: 'unset',
              offset: '0',
              shadow: 'none',
            },
          },
          tabpanel: {
            background: '#ffffff',
            color: '#212529',
            padding: '1.25rem 0 0 0',
            focusRing: {
              width: '0',
              style: 'none',
              color: 'unset',
              offset: '0',
              shadow: 'none',
            },
          },
        },
        dark: {
          root: {
            transitionDuration: '0.2s',
          },
          tablist: {
            borderWidth: '0 0 2px 0',
            background: '#1a1d23',
            borderColor: '#212529',
          },
          tab: {
            background: 'transparent',
            hoverBackground: '#212529',
            activeBackground: '#fdc570',
            borderWidth: '0 0 2px 0',
            borderColor: 'transparent',
            hoverBorderColor: '#212529',
            activeBorderColor: '#fdc570',
            color: '#adb5bd',
            hoverColor: '#e9ecef',
            activeColor: '#000000',
            padding: '1rem 1.25rem',
            fontWeight: '600',
            margin: '0 0 -2px 0',
            gap: '0.5rem',
            focusRing: {
              width: '0',
              style: 'none',
              color: 'unset',
              offset: '0',
              shadow: 'none',
            },
          },
          tabpanel: {
            background: '#1a1d23',
            color: '#e9ecef',
            padding: '1.25rem 0 0 0',
            focusRing: {
              width: '0',
              style: 'none',
              color: 'unset',
              offset: '0',
              shadow: 'none',
            },
          },
        },
      },
    },
    inputtext: {
      colorScheme: {
        light: {
          root: {
            background: '#ffffff',
            disabledBackground: '#f8f9fa',
            filledBackground: '#f8f9fa',
            filledHoverBackground: '#e9ecef',
            filledFocusBackground: '#ffffff',
            borderColor: '#adb5bd',
            hoverBorderColor: '#f87b07',
            focusBorderColor: '#f87b07',
            invalidBorderColor: '#f21b3f',
            color: '#212529',
            disabledColor: '#6c757d',
            placeholderColor: '#6c757d',
          },
        },
        dark: {
          root: {
            background: '#1a1d23',
            disabledBackground: '#1a1d23',
            filledBackground: '#1a1d23',
            filledHoverBackground: '#212529',
            filledFocusBackground: '#1a1d23',
            borderColor: '#212529',
            hoverBorderColor: '#fdc570',
            focusBorderColor: '#fdc570',
            invalidBorderColor: '#f21b3f',
            color: '#f8f9fa',
            disabledColor: '#adb5bd',
            placeholderColor: '#adb5bd',
          },
        },
      },
    },
    dropdown: {
      colorScheme: {
        light: {
          root: {
            background: '#ffffff',
            disabledBackground: '#f8f9fa',
            borderColor: '#adb5bd',
            hoverBorderColor: '#f87b07',
            focusBorderColor: '#f87b07',
            invalidBorderColor: '#f21b3f',
            color: '#212529',
            disabledColor: '#6c757d',
            placeholderColor: '#6c757d',
          },
          dropdown: {
            width: '2.5rem',
            color: '#6c757d',
          },
          overlay: {
            background: '#f8f9fa',
            borderColor: '#e9ecef',
            borderRadius: '0.375rem',
            color: '#212529',
            shadow:
              '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
          },
          list: {
            padding: '0.25rem 0',
            gap: '2px',
          },
          option: {
            focusBackground: '#fdc570',
            selectedBackground: '#f87b07',
            selectedFocusBackground: 'rgb(46, 38, 26)',
            color: '#212529',
            focusColor: '#212529',
            selectedColor: '#ffffff',
            selectedFocusColor: '#ffffff',
            padding: '0.5rem 0.75rem',
            borderRadius: '0.25rem',
          },
        },
        dark: {
          root: {
            background: '#1a1d23',
            disabledBackground: '#1a1d23',
            borderColor: '#212529',
            hoverBorderColor: '#fdc570',
            focusBorderColor: '#fdc570',
            invalidBorderColor: '#f21b3f',
            color: '#e9ecef',
            disabledColor: '#adb5bd',
            placeholderColor: '#adb5bd',
          },
          dropdown: {
            width: '2.5rem',
            color: '#adb5bd',
          },
          overlay: {
            background: '#1a1d23',
            borderColor: '#212529',
            borderRadius: '0.375rem',
            color: '#e9ecef',
            shadow:
              '0 10px 15px -3px rgba(0, 0, 0, 0.25), 0 4px 6px -2px rgba(0, 0, 0, 0.1)',
          },
          list: {
            padding: '0.25rem 0',
            gap: '2px',
          },
          option: {
            focusBackground: '#212529',
            selectedBackground: '#fdc570',
            selectedFocusBackground: '#f87b07',
            color: '#e9ecef',
            focusColor: '#e9ecef',
            selectedColor: '#000000',
            selectedFocusColor: '#000000',
            padding: '0.5rem 0.75rem',
            borderRadius: '0.25rem',
          },
        },
      },
    },
    datatable: {
      colorScheme: {
        light: {
          root: {
            borderColor: '#e9ecef',
            backgroundColor: '#ffffff',
          },
          header: {
            background: '#f8f9fa',
            borderColor: '#e9ecef',
            color: '#212529',
          },
          headerCell: {
            background: '#f8f9fa',
            hoverBackground: '#e9ecef',
            selectedBackground: '#fdc570',
            borderColor: '#e9ecef',
            color: '#212529',
            hoverColor: '#212529',
            selectedColor: '#212529',
            gap: '0.5rem',
            padding: '1rem',
            focusRing: {
              width: '0',
              style: 'none',
              color: 'unset',
              offset: '0',
              shadow: 'none',
            },
          },
          columnTitle: {
            fontWeight: '600',
          },
          row: {
            background: '#ffffff',
            hoverBackground: '#f8f9fa',
            selectedBackground: '#fdc570',
            stripedBackground: '#f8f9fa',
            focusBackground: '#e9ecef',
            color: '#212529',
            hoverColor: '#212529',
            selectedColor: '#212529',
            focusColor: '#212529',
          },
          bodyCell: {
            borderColor: '#e9ecef',
            padding: '1rem',
            focusRing: {
              width: '0',
              style: 'none',
              color: 'unset',
              offset: '0',
              shadow: 'none',
            },
          },
          footerCell: {
            background: '#f8f9fa',
            borderColor: '#e9ecef',
            color: '#212529',
            padding: '1rem',
          },
          columnFooter: {
            fontWeight: '600',
          },
          footer: {
            background: '#f8f9fa',
            borderColor: '#e9ecef',
            color: '#212529',
          },
          dropPointColor: '#f87b07',
          columnResizerWidth: '0.5rem',
        },
        dark: {
          root: {
            borderColor: '#212529',
            backgroundColor: '#1a1d23',
          },
          header: {
            background: '#1a1d23',
            borderColor: '#212529',
            color: '#e9ecef',
          },
          headerCell: {
            background: '#1a1d23',
            hoverBackground: '#212529',
            selectedBackground: '#212529',
            borderColor: '#212529',
            color: '#e9ecef',
            hoverColor: '#e9ecef',
            selectedColor: '#fdc570',
            gap: '0.5rem',
            padding: '1rem',
            focusRing: {
              width: '0',
              style: 'none',
              color: 'unset',
              offset: '0',
              shadow: 'none',
            },
          },
          columnTitle: {
            fontWeight: '600',
          },
          row: {
            background: '#1a1d23',
            hoverBackground: '#212529',
            selectedBackground: '#212529',
            stripedBackground: '#212529',
            focusBackground: '#212529',
            color: '#e9ecef',
            hoverColor: '#e9ecef',
            selectedColor: '#fdc570',
            focusColor: '#e9ecef',
          },
          bodyCell: {
            borderColor: '#212529',
            padding: '1rem',
            focusRing: {
              width: '0',
              style: 'none',
              color: 'unset',
              offset: '0',
              shadow: 'none',
            },
          },
          footerCell: {
            background: '#1a1d23',
            borderColor: '#212529',
            color: '#e9ecef',
            padding: '1rem',
          },
          columnFooter: {
            fontWeight: '600',
          },
          footer: {
            background: '#1a1d23',
            borderColor: '#212529',
            color: '#e9ecef',
          },
          dropPointColor: '#fdc570',
          columnResizerWidth: '0.5rem',
        },
      },
    },
    stepper: {
      colorScheme: {
        light: {
          root: {
            transitionDuration: '0.2s',
          },
          separator: {
            background: '#e9ecef',
            activeBackground: '#f87b07',
            margin: '0 0.5rem',
            size: '2px',
          },
          step: {
            padding: '0.5rem',
            gap: '0.5rem',
          },
          stepHeader: {
            padding: '0',
            borderRadius: '0.375rem',
            focusRing: {
              width: '0',
              style: 'none',
              color: 'unset',
              offset: '0',
              shadow: 'none',
            },
            gap: '0.5rem',
          },
          stepTitle: {
            color: '#6c757d',
            activeColor: '#f87b07',
            fontWeight: '500',
          },
          stepNumber: {
            background: '#e9ecef',
            activeBackground: '#f87b07',
            borderColor: '#e9ecef',
            activeBorderColor: '#f87b07',
            color: '#6c757d',
            activeColor: '#ffffff',
            size: '2rem',
            fontSize: '1.143rem',
            fontWeight: '500',
            borderRadius: '50%',
            shadow: 'none',
          },
          stepPanel: {
            background: '#ffffff',
            color: '#212529',
            padding: '1.25rem 0.5rem',
          },
        },
        dark: {
          root: {
            transitionDuration: '0.2s',
          },
          separator: {
            background: '#212529',
            activeBackground: '#fdc570',
            margin: '0 0.5rem',
            size: '2px',
          },
          step: {
            padding: '0.5rem',
            gap: '0.5rem',
          },
          stepHeader: {
            padding: '0',
            borderRadius: '0.375rem',
            focusRing: {
              width: '0',
              style: 'none',
              color: 'unset',
              offset: '0',
              shadow: 'none',
            },
            gap: '0.5rem',
          },
          stepTitle: {
            color: '#adb5bd',
            activeColor: '#fdc570',
            fontWeight: '500',
          },
          stepNumber: {
            background: '#212529',
            activeBackground: '#fdc570',
            borderColor: '#212529',
            activeBorderColor: '#fdc570',
            color: '#adb5bd',
            activeColor: '#000000',
            size: '2rem',
            fontSize: '1.143rem',
            fontWeight: '500',
            borderRadius: '50%',
            shadow: 'none',
          },
          stepPanel: {
            background: '#1a1d23',
            color: '#e9ecef',
            padding: '1.25rem 0.5rem',
          },
        },
      },
    },
  },
});
