import { definePreset } from '@primeng/themes';
import Aura from '@primeng/themes/aura';

export const PrimeCustomPreset = definePreset(Aura, {
  semantic: {
    primary: {
      50: '#fdc570',
      100: '#fdc570',
      200: '#fdc570',
      300: '#f87b07',
      400: '#f87b07',
      500: '#f87b07',
      600: '#f87b07',
      700: '#f87b07',
      800: '#fdc570',
      900: '#fdc570',
      950: '#fdc570',
    },
    secondary: {
      50: '#212529',
      100: '#212529',
      200: '#212529',
      300: '#212529',
      400: '#212529',
      500: '#212529',
      600: '#212529',
      700: '#212529',
      800: '#212529',
      900: '#212529',
      950: '#212529',
    },
    colorScheme: {
      light: {
        primary: {
          color: '#f87b07',
          contrastColor: '#ffffff',
          hoverColor: '#fdc570',
          activeColor: 'rgb(46, 38, 26)',
        },
        highlight: {
          background: '#f87b07',
          focusBackground: '#fdc570',
          color: '#ffffff',
          focusColor: '#f8f9fa',
        },
        surface: {
          0: '#f8f9fa',
          50: '#f8f9fa',
          100: '#f8f9fa',
          200: '#f8f9fa',
          300: '#e9ecef',
          400: '#e9ecef',
          500: '#e9ecef',
          600: '#e9ecef',
          700: '#e9ecef',
          800: '#e9ecef',
          900: '#e9ecef',
          950: '#e9ecef',
        },
        content: {
          color: '#212529',
          hoverColor: '#f87b07',
          activeColor: 'rgb(46, 38, 26)',
        },
      },
      dark: {
        primary: {
          color: '#fdc570',
          contrastColor: '#000000',
          hoverColor: '#f87b07',
          activeColor: 'rgb(46, 38, 26)',
        },
        highlight: {
          background: '#fdc570',
          focusBackground: '#f87b07',
          color: '#000000',
          focusColor: '#1a1d23',
        },
        surface: {
          0: '#1a1d23',
          50: '#1a1d23',
          100: '#1a1d23',
          200: '#1a1d23',
          300: '#212529',
          400: '#212529',
          500: '#212529',
          600: '#212529',
          700: '#212529',
          800: '#212529',
          900: '#212529',
          950: '#212529',
        },
        content: {
          color: '#e9ecef',
          hoverColor: '#fdc570',
          activeColor: '#f87b07',
        },
      },
    },
  },
  components: {
    button: {
      colorScheme: {
        light: {
          root: {
            primary: {
              background: '#f87b07',
              hoverBackground: '#fdc570',
              activeBackground: 'rgb(46, 38, 26)',
              borderColor: '#f87b07',
              hoverBorderColor: '#fdc570',
              activeBorderColor: 'rgb(46, 38, 26)',
              color: '#ffffff',
              hoverColor: '#ffffff',
              activeColor: '#ffffff',
            },
            secondary: {
              background: 'rgb(46, 38, 26)',
              hoverBackground: '#6c757d',
              activeBackground: '#adb5bd',
              borderColor: 'rgb(46, 38, 26)',
              hoverBorderColor: '#6c757d',
              activeBorderColor: '#adb5bd',
              color: '#ffffff',
              hoverColor: '#ffffff',
              activeColor: '#ffffff',
            },
            success: {
              background: 'rgb(46, 38, 26)',
              hoverBackground: '#fdc570',
              activeBackground: '#f87b07',
              borderColor: 'rgb(46, 38, 26)',
              hoverBorderColor: '#fdc570',
              activeBorderColor: '#f87b07',
              color: '#ffffff',
              hoverColor: '#ffffff',
              activeColor: '#ffffff',
            },
            warn: {
              background: '#ff9914',
              hoverBackground: '#ff9914',
              activeBackground: '#ff9914',
              borderColor: '#ff9914',
              hoverBorderColor: '#ff9914',
              activeBorderColor: '#ff9914',
              color: '#000000',
              hoverColor: '#000000',
              activeColor: '#ffffff',
            },
            danger: {
              background: '#f21b3f',
              hoverBackground: '#f21b3f',
              activeBackground: '#f21b3f',
              borderColor: '#f21b3f',
              hoverBorderColor: '#f21b3f',
              activeBorderColor: '#f21b3f',
              color: '#ffffff',
              hoverColor: '#ffffff',
              activeColor: '#ffffff',
            },
          },
        },
        dark: {
          root: {
            primary: {
              background: '#fdc570',
              hoverBackground: '#f87b07',
              activeBackground: 'rgb(46, 38, 26)',
              borderColor: '#fdc570',
              hoverBorderColor: '#f87b07',
              activeBorderColor: 'rgb(46, 38, 26)',
              color: '#000000',
              hoverColor: '#000000',
              activeColor: '#000000',
            },
            secondary: {
              background: '#adb5bd',
              hoverBackground: '#6c757d',
              activeBackground: '#212529',
              borderColor: '#adb5bd',
              hoverBorderColor: '#6c757d',
              activeBorderColor: '#212529',
              color: '#000000',
              hoverColor: '#000000',
              activeColor: '#000000',
            },
            success: {
              background: 'rgb(46, 38, 26)',
              hoverBackground: '#fdc570',
              activeBackground: '#f87b07',
              borderColor: 'rgb(46, 38, 26)',
              hoverBorderColor: '#fdc570',
              activeBorderColor: '#f87b07',
              color: '#ffffff',
              hoverColor: '#ffffff',
              activeColor: '#ffffff',
            },
            warn: {
              background: '#ff9914',
              hoverBackground: '#ff9914',
              activeBackground: '#ff9914',
              borderColor: '#ff9914',
              hoverBorderColor: '#ff9914',
              activeBorderColor: '#ff9914',
              color: '#000000',
              hoverColor: '#000000',
              activeColor: '#000000',
            },
            danger: {
              background: '#f21b3f',
              hoverBackground: '#f21b3f',
              activeBackground: '#f21b3f',
              borderColor: '#f21b3f',
              hoverBorderColor: '#f21b3f',
              activeBorderColor: '#f21b3f',
              color: '#ffffff',
              hoverColor: '#ffffff',
              activeColor: '#ffffff',
            },
          },
        },
      },
    },
    card: {
      colorScheme: {
        light: {
          root: {
            background: '#f8f9fa',
            color: '#212529',
          },
          subtitle: {
            color: '#6c757d',
          },
        },
        dark: {
          root: {
            background: '#1a1d23',
            color: '#e9ecef',
          },
          subtitle: {
            color: '#adb5bd',
          },
        },
      },
    },
    panel: {
      colorScheme: {
        light: {
          root: {
            background: '#f8f9fa',
            borderColor: '#adb5bd',
            color: '#212529',
          },
          header: {
            background: '#f8f9fa',
            borderColor: '#adb5bd',
            color: '#f87b07',
          },
        },
        dark: {
          root: {
            background: '#1a1d23',
            borderColor: '#212529',
            color: '#e9ecef',
          },
          header: {
            background: '#1a1d23',
            borderColor: '#212529',
            color: '#fdc570',
          },
        },
      },
    },
    inputtext: {
      colorScheme: {
        light: {
          root: {
            background: '#ffffff',
            disabledBackground: '#f8f9fa',
            filledBackground: '#f8f9fa',
            filledHoverBackground: '#e9ecef',
            filledFocusBackground: '#ffffff',
            borderColor: '#adb5bd',
            hoverBorderColor: '#f87b07',
            focusBorderColor: '#f87b07',
            invalidBorderColor: '#f21b3f',
            color: '#212529',
            disabledColor: '#6c757d',
            placeholderColor: '#6c757d',
          },
        },
        dark: {
          root: {
            background: '#1a1d23',
            disabledBackground: '#1a1d23',
            filledBackground: '#1a1d23',
            filledHoverBackground: '#212529',
            filledFocusBackground: '#1a1d23',
            borderColor: '#212529',
            hoverBorderColor: '#fdc570',
            focusBorderColor: '#fdc570',
            invalidBorderColor: '#f21b3f',
            color: '#e9ecef',
            disabledColor: '#adb5bd',
            placeholderColor: '#adb5bd',
          },
        },
      },
    },
    dropdown: {
      colorScheme: {
        light: {
          root: {
            background: '#ffffff',
            disabledBackground: '#f8f9fa',
            borderColor: '#adb5bd',
            hoverBorderColor: '#f87b07',
            focusBorderColor: '#f87b07',
            invalidBorderColor: '#f21b3f',
            color: '#212529',
            disabledColor: '#6c757d',
            placeholderColor: '#6c757d',
          },
          dropdown: {
            width: '2.5rem',
            color: '#6c757d',
          },
          overlay: {
            background: '#f8f9fa',
            borderColor: '#e9ecef',
            borderRadius: '0.375rem',
            color: '#212529',
            shadow:
              '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
          },
          list: {
            padding: '0.25rem 0',
            gap: '2px',
          },
          option: {
            focusBackground: '#fdc570',
            selectedBackground: '#f87b07',
            selectedFocusBackground: 'rgb(46, 38, 26)',
            color: '#212529',
            focusColor: '#212529',
            selectedColor: '#ffffff',
            selectedFocusColor: '#ffffff',
            padding: '0.5rem 0.75rem',
            borderRadius: '0.25rem',
          },
        },
        dark: {
          root: {
            background: '#1a1d23',
            disabledBackground: '#1a1d23',
            borderColor: '#212529',
            hoverBorderColor: '#fdc570',
            focusBorderColor: '#fdc570',
            invalidBorderColor: '#f21b3f',
            color: '#e9ecef',
            disabledColor: '#adb5bd',
            placeholderColor: '#adb5bd',
          },
          dropdown: {
            width: '2.5rem',
            color: '#adb5bd',
          },
          overlay: {
            background: '#1a1d23',
            borderColor: '#212529',
            borderRadius: '0.375rem',
            color: '#e9ecef',
            shadow:
              '0 10px 15px -3px rgba(0, 0, 0, 0.25), 0 4px 6px -2px rgba(0, 0, 0, 0.1)',
          },
          list: {
            padding: '0.25rem 0',
            gap: '2px',
          },
          option: {
            focusBackground: '#212529',
            selectedBackground: '#fdc570',
            selectedFocusBackground: '#f87b07',
            color: '#e9ecef',
            focusColor: '#e9ecef',
            selectedColor: '#000000',
            selectedFocusColor: '#000000',
            padding: '0.5rem 0.75rem',
            borderRadius: '0.25rem',
          },
        },
      },
    },
  },
});
