export enum BankCode {
  BancoDoBrasil = '001',
  Santander = '033',
  Caixa = '104',
  Bradesco = '237',
  Itau = '341',
  Safra = '422',
  BancoInter = '077',
  Nubank = '260',
  Caju = '301',
  Pluxee = '369',
  C6Bank = '336',
  Original = '212',
  Neon = '655',
  PagSeguro = '290',
  Mercado_Pago = '323',
  PicPay = '380',
  Stone = '197',
  Banrisul = '041',
  BTGPactual = '208',
  Sicoob = '756',
  Sicredi = '748',
  PineBank = '643',
  BancoBS2 = '218',
  IfoodPago = '435',
  Alelo = '373',
  Ticket = '374',
}

export const BANK_CODE_LABELS: Record<BankCode, string> = {
  [BankCode.BancoDoBrasil]: 'Banco do Brasil',
  [BankCode.Santander]: 'Santander',
  [BankCode.Caixa]: 'Caixa Econômica Federal',
  [BankCode.Bradesco]: 'Bradesco',
  [BankCode.Itau]: 'Itaú Unibanco',
  [BankCode.Safra]: 'Safra',
  [BankCode.BancoInter]: 'Inter',
  [BankCode.Nubank]: 'Nubank',
  [BankCode.Caju]: 'Caju',
  [BankCode.C6Bank]: 'C6',
  [BankCode.Original]: 'Original',
  [BankCode.Neon]: 'Neon',
  [BankCode.PagSeguro]: 'PagSeguro',
  [BankCode.Mercado_Pago]: 'Mercado Pago',
  [BankCode.PicPay]: 'PicPay',
  [BankCode.Stone]: 'Stone',
  [BankCode.Banrisul]: 'Banrisul',
  [BankCode.BTGPactual]: 'BTG Pactual',
  [BankCode.Sicoob]: 'Sicoob',
  [BankCode.Sicredi]: 'Sicredi',
  [BankCode.PineBank]: 'Pine',
  [BankCode.BancoBS2]: 'BS2',
  [BankCode.IfoodPago]: 'iFood Pago',
  [BankCode.Alelo]: 'Alelo',
  [BankCode.Ticket]: 'Ticket',
  [BankCode.Pluxee]: 'Pluxee',
};
export const BANK_ICON_MAP: Record<BankCode, string> = {
  [BankCode.BancoDoBrasil]: 'bancodobrasil',
  [BankCode.Santander]: 'santander',
  [BankCode.Caixa]: 'caixa',
  [BankCode.Bradesco]: 'bradesco',
  [BankCode.Itau]: 'itau',
  [BankCode.Safra]: 'safra',
  [BankCode.BancoInter]: 'inter',
  [BankCode.Nubank]: 'nubank',
  [BankCode.Caju]: 'caju',
  [BankCode.C6Bank]: 'c6',
  [BankCode.Original]: 'original',
  [BankCode.Neon]: 'neon',
  [BankCode.PagSeguro]: 'pagseguro',
  [BankCode.Mercado_Pago]: 'mercadopago',
  [BankCode.PicPay]: 'picpay',
  [BankCode.Stone]: 'stone',
  [BankCode.Banrisul]: 'banrisul',
  [BankCode.BTGPactual]: 'btg',
  [BankCode.Sicoob]: 'sicoob',
  [BankCode.Sicredi]: 'sicredi',
  [BankCode.PineBank]: 'pine',
  [BankCode.BancoBS2]: 'bs2',
  [BankCode.IfoodPago]: 'ifood',
  [BankCode.Alelo]: 'alelo',
  [BankCode.Ticket]: 'ticket',
  [BankCode.Pluxee]: 'pluxee',
};
